spring:  
  application:
    name: order-service
  rabbitmq:
    host: localhost
    port: 5672
  cloud:  
    stream:
      bindings:
        output:
          destination: orders-out
        input:
          destination: orders-in
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: direct
              routingKeyExpression: '"#"'
          input:
            consumer:
              exchangeType: direct

server:  
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true